# topics.yml (雛形)
#
# トピック定義の例。必要に応じて増減・修正してください。
# - name: 財政
#   keywords: [予算, 決算, 税収, 歳出, 歳入]
# - name: 福祉
#   keywords: [子育て, 高齢者, 介護, 障害, 生活保護]
# - name: 教育
#   keywords: [学校, 学級, 教員, 学力, ICT]

