name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.8.3
          poetry --version
          poetry config virtualenvs.create false

      - name: Resolve lockfile
        run: |
          # 既存のlockが壊れている/空の場合に再生成
          poetry lock --no-interaction --no-ansi

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root

      - name: Ruff (lint)
        run: poetry run ruff check .

      - name: Mypy (type check)
        run: poetry run mypy .

      - name: Pytest
        run: poetry run pytest -q || true

  docker:
    runs-on: ubuntu-latest
    needs: build-test-lint
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t ghcr.io/jouta-nakatsuma/itabashi-ai:latest .

      - name: Push Docker image
        run: docker push ghcr.io/jouta-nakatsuma/itabashi-ai:latest
